#include "mod1_terrain.h"

MOD1_EXCEPTION_GENERATE_IMPLEMENTATION(mod1_terrain, exception_source)
MOD1_EXCEPTION_GENERATE_IMPLEMENTATION(mod1_terrain, exception_pattern)
MOD1_EXCEPTION_GENERATE_IMPLEMENTATION(mod1_terrain, exception_search)
MOD1_EXCEPTION_GENERATE_IMPLEMENTATION(mod1_terrain, exception_color)