#pragma once

#include "mod1_macros.h"

//											GLOBAL

#define MOD1_NORMAL_TEST					MOD1_DISABLE

#if MOD1_ENABLED(MOD1_NORMAL_TEST)
#define MOD1_SOURCE_SHADER_VERTEX			"./shaders/test_vertex.glsl"
#define MOD1_SOURCE_SHADER_GEOMETRY			"./shaders/test_geometry.glsl"
#define MOD1_SOURCE_SHADER_FRAGMENT			"./shaders/test_fragment.glsl"
#else
#define MOD1_SOURCE_SHADER_VERTEX			"./shaders/vertex.glsl"
#define MOD1_SOURCE_SHADER_FRAGMENT			"./shaders/fragment.glsl"
#endif

//											ENGINE

#define MOD1_DEPTH_TEST						MOD1_ENABLE
#define MOD1_SHOW_BACK_OF_POLYGON			MOD1_ENABLE
#define MOD1_SRGB							MOD1_DISABLE

#define MOD1_LIGHT_AMBIENT_INTENSITY		0.2
#define MOD1_LIGHT_POINT_INTENSITY			0.8
#define MOD1_LIGHT_POINT_POSITION			50, 100, 50

#define MOD1_LIGHT_CUBE						MOD1_ENABLE
#define MOD1_LIGHT_CUBE_SIDE				4

#define MOD1_CAMERA_POSITION				glm::vec3(20, 20, 50)
#define MOD1_CAMERA_MOVEMENT_SPEED			5
#define MOD1_CAMERA_ROTATION_SPEED			0.04

#define MOD1_BACKGROUND						mod1_point3<float>(0.1)

//											MAIN

#define MOD1_USE_TERRAIN					MOD1_ENABLE
#define MOD1_USE_WATER						MOD1_DISABLE

//											TERRAIN

#define MOD1_TERRAIN_NOISE					MOD1_DISABLE

#define MOD1_TERRAIN_NOISE_HILL				MOD1_ENABLE
#define MOD1_TERRAIN_NOISE_HILL_FREQUENCY	0.2
#define MOD1_TERRAIN_NOISE_HILL_RANGE		200
#define MOD1_TERRAIN_NOISE_HILL_ADD			0.8

#define MOD1_TERRAIN_NOISE_A				MOD1_ENABLE
#define MOD1_TERRAIN_NOISE_A_FREQUENCY		0.015
#define MOD1_TERRAIN_NOISE_A_RANGE			5000

#define MOD1_TERRAIN_NOISE_B				MOD1_ENABLE
#define MOD1_TERRAIN_NOISE_B_FREQUENCY		0.05
#define MOD1_TERRAIN_NOISE_B_RANGE			400

//											WATER

#define MOD1_WATER_FLOOD_UNIFORM

#define MOD1_WATER_CONST_A					1000
#define MOD1_WATER_CONST_g					10
#define MOD1_WATER_CONST_dt					50000

#define MOD1_WATER_HIDDEN					-1000

#define MOD1_WATER_COLOR_A					0, 0.62, 1
#define MOD1_WATER_COLOR_B					0, 0.05, 0.1
#define MOD1_WATER_COLOR_RANGE				10000