#include "terrain.h"

MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(terrain, exception_source)
MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(terrain, exception_pattern)
MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(terrain, exception_search)