#include "plane.h"

using namespace		mod1_algorithm;

MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(plane, exception_coordinate)
MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(plane, exception_logic)
MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(plane, exception_color)
MOD1_GENERATE_EXCEPTION_IMPLEMENTATION(plane, exception_indexing_convention)

MOD1_GENERATE_GET_IMPLEMENTATION(plane, size)
MOD1_GENERATE_GET_IMPLEMENTATION(plane, real_size)
MOD1_GENERATE_GET_IMPLEMENTATION(plane, min)
MOD1_GENERATE_GET_IMPLEMENTATION(plane, max)
MOD1_GENERATE_GET_IMPLEMENTATION(plane, delta)
MOD1_GENERATE_GET_IMPLEMENTATION(plane, final_min)
MOD1_GENERATE_GET_IMPLEMENTATION(plane, final_max)